"""Adding Course_Material Table

Revision ID: 438e9caedfa8
Revises: eda3cb23f1bc
Create Date: 2024-02-10 10:17:24.980953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '438e9caedfa8'
down_revision: Union[str, None] = 'eda3cb23f1bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Course_Material',
    sa.Column('course_material_id', sa.Integer(), nullable=False),
    sa.Column('course_material_url', sa.String(length=100), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['Course.course_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('course_material_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Course_Material')
    # ### end Alembic commands ###
