"""Adding Student Course Table

Revision ID: e7aaecfa8053
Revises: 438e9caedfa8
Create Date: 2024-02-10 19:13:19.866697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e7aaecfa8053'
down_revision: Union[str, None] = '438e9caedfa8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Student_Course',
    sa.Column('table_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['Course.course_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['Student.student_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('table_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Student_Course')
    # ### end Alembic commands ###
