"""Adding Teacher table

Revision ID: eda3cb23f1bc
Revises: 03460850a699
Create Date: 2024-02-10 09:42:18.870694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'eda3cb23f1bc'
down_revision: Union[str, None] = '03460850a699'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Teacher',
    sa.Column('teacher_first_name', sa.String(length=50), nullable=False),
    sa.Column('teacher_last_name', sa.String(length=50), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('teacher_email', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('teacher_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Teacher')
    # ### end Alembic commands ###
